name: simple_mensa
description: "A Mensa app written in Flutter"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.8
  dio: ^5.5.0+1
  flutter_bloc: ^8.1.6
  json_annotation: ^4.9.0
  objectbox: ^4.0.1
  objectbox_flutter_libs: any
  path: ^1.9.0
  path_provider: ^2.1.3
  retrofit: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  objectbox_generator: any
  retrofit_generator: ^8.1.1

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
